# Python 기초 문법

`작성자: 최원칠 강사`   
`traveler4d@gmail.com`


### 주요 내용

1. 파이썬의 기본 정의와 데이터 타입에 대한 이해
2. 파이썬 기본 제어문에 대한 이해
3. 파이썬 기본 데이터구조에 대한 이해





<br>

## 1. 형식의 이해



### 1.1. 변수 할당

파이썬은 데이터를 컴퓨터구조중 메모리의 특정 주소에 저장.   
저장된 데이터를 사용하기 위해선 복잡한 주소를 통해 데이터를 접근해야함.  
이때 복잡한 주소대신 개발자가 기억하기 쉬운 특정 단어로 데이터를 찾아가기 위해 변수사용.    
이렇게 변수를 통해 데이터의 주소를 `참조`한다 또는 `할당`한다라는 표현을 사용.

<img src="./img/20240601_215348.png"  width = 360 align="center"></img>  


#### 변수 이름 규칙
- 소문자 영단어
- 2개이상의 단어 사용시 _ 로 단어구분 ex) my_num
- _ 를 제외한 특수문자 사용 금지
- 숫자 사용시 영단어 뒤에 배치 ex) num1

In [1]:
# 할당(assign), 저장의 의미를 가짐
#     적절한 표현의 변수이름을 지정하고 = 을 활용하여 할당
num = 10
num

10

In [2]:
# 이미 할당된 변수에 = 을 사용하면 재할당이 이루어짐
num = 10
num = 11
num

11

In [3]:
# 변수에 할당이 이루어진 또다른 변수 할당 가능
#     print()를 활용하여 데이터를 터미털(또는 셸)에 출력 가능
num1 = 10
num2 = num1
print(num1)
print(num2)

10
10


In [4]:
# 할당은 참조의 개념임을 유의할 것
num1 = 10
num2 = num1
num1 = 11
print(num1)
print(num2)

11
10


<img src="./img/20231207_123708.png"  width = 700 align="left"></img>  


### 1.2. 데이터 타입과 연산자

파이썬에서 데이터는 모두 객체로 이루어져 있어 객체에 따른 **타입(type)** 을 가짐.    
파이썬은 다음과 같이 기본적인 자료형 데이터를 객체로 제공   

* int : 정수
* float : 소수점, 비율을 포함한 실수
* str : 문자열
* bool : True와 False

데이터 타입에 따라 연산자의 활용용도가 달라짐


#### int, float
정수와 실수를 나타냄

In [6]:
# 정수형 타입
#     type() 을 활용하여 데이터의 타입 확인 가능
num = 10
type(num)

int

In [7]:
# 실수형 타입
num = 10.1
type(num)

float

In [8]:
# 정수형 간의 연산자 활용
#     숫자형 사칙연산 +, -, *, /, //, %, **
num1 = 10
num2 = 20
num1 + num2

30

#### 숫자형과 산술연산
 `+`: 더하기   
 `-`: 빼기   
 `*`: 곱하기   
 `/` : 나누기   
 `//` : 몫   
 `**` : 제곱   

In [9]:
# 실수형 혼합 연산
num1 = 10
num2 = 10.1
num1 + num2

20.1

In [10]:
# 나누기 연산시 실수형으로 변환
num1 = 10
num2 = 20
num2 / num1

2.0

#### 대입연산

`a += b` : `a = a+b`   
`a +- b` : `a = a-b`


In [11]:
# += 을 활용하여 누적 연산 가능
num = 10
num += 10 # num = num + 10
num

20

#### str
문자의 집합인 텍스트를 나타냄

In [18]:
# 문자열 타입 
#     파이썬은 단일 문자타입 대신 문자열 타입만 존재
#     '', "" 둘다 사용가능
name1 = '파이썬'
name2 = "기초"
print(type(name1))
print(type(name2))

<class 'str'>
<class 'str'>


- **리터럴**: 특정 기호나 숫자로 데이터를 생성하는 과정

In [19]:
# 문자열 간의 연산 활용
#     문자열간 연산은 숫자형과 다르게 적용
name1 = '파이썬'
name2 = '기초'
name1 + name2

'파이썬기초'

In [20]:
# 문자열과 숫자형 연산 가능
name = '파이썬'
num = 3
name * num

'파이썬파이썬파이썬'

In [15]:
# 문자열의 포맷 방법
#     다양한 변수를 하나의 문자열로 생성   
#     ''.format() 또는 f''를 이용

num = 1
name = '파이썬'

print('{}일차 {} 수업에 오신걸 환영합니다'.format(num, name))
print(f'{num}일차 {name} 수업에 오신걸 환영합니다')

1일차 파이썬 수업에 오신걸 환영합니다
1일차 파이썬 수업에 오신걸 환영합니다


#### bool
True와 False로 표현됨

In [16]:
# bool 타입
#     False는 0, True는 0이외의 값으로 표현
t = True
f = False
type(t)

bool

#### 비교연산
 `==` : 값이 같으면 True  
 `!=` : 값이 다르면 True  
 `>, >=, <, <=` : 대소비교 성립시 True  
 `is` : 타입과 값이 같으면 True  
#### 논리연산
 `and` : 둘다 True이면 True   
 `or`: 둘중 하나라도 True 이면 True  
 `not`: True 이면 False (역변환)  

In [17]:
# 비교연산자의 활용
num1 = 100
num2 = 10

print(num1 == num2)
print(num1 != num2)
print(num1 > num2)
print(num1 <= num2)


False
True
True
False


In [18]:
# 논리 연산 활용
print(not True)
print(True and True)
print(True and False)
print(True or False)
print(False or False)

False
True
False
True
False


#### NoneType
데이터가 없다는 의미를 뜻하는 타입

In [5]:
is_on = None
print(is_on)
print(type(is_on))

None
<class 'NoneType'>


#### 데이터 타입 변환 (형변환)

- int(): () 안의 변수 또는 데이터를 int 객체로 변환
- float(): () 안의 변수 또는 데이터를 float 객체로 변환
- str(): () 안의 변수 또는 데이터를 str 객체로 변환
- bool(): () 안의 변수 또는 데이터를 bool 객체로 변환

In [1]:
# 파이썬에서 int(),float(),str()등 내장함수로 제공 

num1 = int(10.1)
num2 = float(10)
num3 = int('10')
num4 = str(10)
print(num1, num2, num3, num4)
print(type(num1), type(num2), type(num3), type(num4))

10 10.0 10 10
<class 'int'> <class 'float'> <class 'int'> <class 'str'>


### 1.3. 함수
일시적인 기능을 수행 (일회성 데이터)하기 위한 정의

#### def을 통해 특정 기능을 수행하는 함수 정의

    def 함수이름(인자1,인자2):
        code
        return 반환
    
- **인자** : 함수 실행시 필요한 입력 데이터(input) 
- **반환** : 함수 실행후 결과로 제공될 출력 데이터(output)

1. `def`명령어 옆에 이름 정의.
2. 이름옆 `()`안에 인자를 정의 `,` 구분으로 여러개 정의 가능. 이렇게 정의한 인자는 def code에서 변수로 활용.    
3. def code영역은 함수가 호출될때 실행되는 코드 `:` 이후 `들여쓰기(TAB)`으로 작성.  
4. def code영역에서 `return` 명령어 뒤에 출력할 데이터 또는 변수를 작성. return 명령어가 나오면 함수실행 종료   


In [21]:
# def 을 통한 함수 정의
#     파이썬은 TAB(들여쓰기)기준으로 코드 실행영역을 지정


def concat(arg1, arg2, arg3=10): # 함수이름은 모두 소문자 단어구분 _
    cat = arg1 + arg2 + arg3
    return cat

# 함수 이름을 통한 함수 실행(사용)
out1 = concat(10, 20)
print(out1)
out2 = concat(10, 20, arg3=30)
print(out2)

40
60


#### 로컬 영역(함수내부)에서 생성된 변수는 로컬변수로 글로벌영역에서 접근 불가
- 글로벌 -> 로컬 읽기 불가능
- 로컬 -> 글로벌 읽기 가능
- 로컬 -> 글로벌 쓰기 불가능

로컬변수는 해당 영역 실행이 끝나는순간 사라지기때문.

In [22]:
# 함수 내부의 변수는 외부에서 접근 불가(return 제외)
#     인자(parameter)와 반환(return)적절히 활용 
    
def fun1():
    data1 = 100 # 로컬 영역

fun1()
print(data1) # 글로벌 영역

NameError: name 'data1' is not defined

In [ ]:
# 인자와 반환을 활용
def local(a , b):  # 로컬 변수(인자)
    c = a+b        # 로컬 변수
    return c

d = local(10,20)   # 글로벌 변수
d

### 1.4 객체
객체는 지속적인 구조체를 이루기위한 존재 (지속적 데이터) 정의    
파이썬에서는 데이터자체가 객체를 의미하며, **객체이름(객체명)** 이 곧 **데이터타입**이됨

<img src="./img/20231207_123311.png"  width = 600 align="center"></img>  



#### 실제 객체는 class라는 명령어로 정의

    class 객체이름:
        self.변수 및 메소드

- **클래스** : 각종 데이터와 기능을 내포시킨 객체의 정의(코드상태)
- **인스턴스** : 정의상태인 클래스가 실행되어 실질적으로 존재하는 상태(지속데이터)
- **self 변수** : 클래스 내부에서만 글로벌 변수 (글로벌 > 셀프 > 로컬)
- **메소드** : 클래스 내부에서 정의된 함수 (self 인자필요)

In [4]:
# class를 통해 객체 정의 

class Product: #클래스 이름은 맨앞글자 대문자 단어구분 대문자
    
    def __init__(self, name, price): # 생성자 메소드 클래스->인스턴스 과정에 실행되는 함수
        self.name = name # self.name 변수와 name 지역변수는 다른 변수
        self.price = price
        self.cate = 'Aiot'
        
    def get_name(self): # 메소드 정의 인스턴스 상태일때 .으로 사용 
        return self.name

    def set_price(self, price):
        self.price = price


#### 정의된 클래스를 실행하여 변수에 할당하면 **인스턴스**
- 인스턴스의 데이터타입은 클래스의 이름
- 인스턴스에서 .(도트연산)을 통해 클래스에서 정의된 메소드, self변수 사용

In [5]:
# 클래스 이름을 호출하여 실행, 변수에 할당하여 인스턴스화


product = Product('팜봇', 500000) # 클래스 실행 인자는 __init__ 함수의 인자
print(type(product))
name = product.get_name() # 인스턴스 변수에서 .(도트연산) 활용
print(name)
print(product.name) # 셀프 변수 사용

product.set_price(600000)
print(product.price)


<class '__main__.Product'>
팜봇
팜봇
600000


### 1.5 모듈

**파이썬 모듈**
- 변수, 함수, 객체를 모두 포함하는 파이썬에서 가장 큰 단위의 정의
- 기본적으로 코드를 작성하고 있는 스크립트 페이지가 모듈 영역
- .py 파일 확장자를 가짐
- 모듈에서 생성된 변수는 글로벌 변수로 취급됨
- 모듈 내에서 다른 소스코드가 작성된 모듈을 가져올 수 있음 수 있음


In [1]:
# 모듈 가져오기
# import 명령어 활용
import os 
# as 명령어로 모듈을 특정 변수이름에 할당
import collections as ct
# from 명령어로 모듈내 특정 정의만 import
from pathlib import Path

# 모듈 사용하기
cwd = os.getcwd()
dq = ct.deque()
path = Path('/.')



### 1. 실습 

#### [실습1] x에 10.1을 저장하고, y에 101을 저장한 다음 더한후 정수로 출력

#### [실습2] a=1, b=5로 할당하고 문자열 포맷으로 'a + b는'과 a+b 계산 결과를 print( )로 함께 출력

출력 결과 예시  
`1 + 5는 6`

#### [실습3] 초를 나타내는 time 값을 다음과 같이 시간,분,초로 나타내는 포맷으로 변경하세요
- `//` : 나누기의 몫만 반환
- `%` : 나머지를 반환

`5000초는 1시간 23분 20초 입니다.`

In [20]:
time = 5000

#### [실습4] 다음 정의된 함수를 실행하고, 반환된 값을 출력하세요

In [1]:
def info(name):
    text = f'어서오세요 {name}님'
    return text

#### [실습5] 실습3의 초변환 기능을 함수로 정의하세요, 이때 초가 입력되는 time인자을 정의하고 만들어진 문자열이 반환되는 return을 정의하세요 


#### [실습6] 다음 클래스(Member)를 활용해 자신의 이름과 나이가 들어간 인스턴스 생성하고, print_info() 함수를 통해 다음 문구 출력

`저의 이름은 000, 나이는 00 입니다.`

In [27]:
class Member:
    def __init__(self, name, age):
        self.name = name
        self.age = age 
        
    def print_info(self):
        return f'저의 이름은 {self.name} 나이는 {self.age} 입니다.'

#### [실습7] 다음 요구사항을 만족하는 클래스를 생성하세요    

**Customer 클래스 정의**  

- 생성자    
    - 인자: 고객 이름(name)과 고객 번호(c_id)
    - 인자로 입력된 데이터를 셀프변수에 저장
    - 0이 할당된 계좌금액 셀프변수 생성
- add_amount 함수 생성
    - 인자: 입금 금액
    - 계좌금액 셀프변수에 입금 금액 추가
    - self.a = self.a + inp => self.a += inp
- sub_amount 함수 생성
    - 인자: 출금 금액
    - 계좌금액 셀프변수에 출금 금액 차감
- get_amount 함수 생성
    - 계좌금액 셀프변수 반환수 생
get_amount 함수 생성
계좌금액 셀프변수 반환
 


#### [실습8] Customer 인스턴스를 생성하여 다음과 같은 구성을 만드세요
- 임의의 고객명과 고객번호를 가지는 Customer 인스턴스를 2개 생성하고 변수에 가각 할당하세요
- 첫번째 고객의 계좌금액을 5000 추가하세요
- 두번째 고객의 계좌금액을 3000 추가하세요
- 두 고객의 계좌금액을 출력하세요
- 첫번째 고객의 계좌금액을 2000 차감하세요
- 두번째 고객의 계좌금액을 1000 차감하세요
- 두 고객의 계좌금액을 출력하세요

In [28]:
myclass = Myclass(15)
myclass.add_num(5)
myclass.get_num()

NameError: name 'Myclass' is not defined

<br>

## 2. 흐름 제어문의 활용


프로그램이 완성되기 위해서는 데이터 뿐만 아니라 데이터를 상황에 맞게 제어필요.    
파이썬에서 데이터를 제어하는 문법은 크게 두가지로 조건문과 반복문 존재. 

### 2.1. if 조건문  

조건문은 프로그램의 진행 흐름에 있어 분기점을 제공.  
파이썬에서 조건문은 `if`,`elif`,`else` 명령어로 구성.

    if bool데이터 :
        code
    else:
        code
    
**if** 명령어 옆에 오는 bool 데이터를 체크하여 코드 실행여부 판단.   
만약 True가 오면 if문의 `: 들여쓰기` 영역의 코드를 실행하고 False인 경우 else문의 `: 들여쓰기` 영역 코드를 실행.


In [2]:
# if의 활용
point=200

if point >=100:
    print('vip') # True인 경우 실행

vip


In [3]:
# if와 else의 활용
point=50

if point >=100:
    print('vip') # True인 경우 실행
else:
    print('일반회원') # False인 경우 실행

normal


In [6]:
# if와 elif와 else의 활용

point = None # 결측 (데이타 없음을 의미)

if point is None: # is : 타입까지 동일해야 True
    print('비회원')
else:
    if point >=100:
        print('vip')
    else:
        print('일반회원')

비회원


In [8]:
point = 140

if point is None:
    print('비회원')
elif point >=200:
    print('vvip')
elif point >=100:
    print('vip')
else:
    print('일반회원')

vip


<br>

### 2.2. for 반복문
**for**는 반복 대상을 지정하고 특정한 명령을 반복 실행

    for 변수 in 이터러블:
        반복코드
     
- **이터러블**: 여러개의 데이터를 가지고있으며, 데이터를 순서대로 출력가능한 구조


<img src="./img/20231207_123936.png"  width = 400 align="left"></img>  


#### 이터러블을 활용한 반복

In [15]:
# 대표적인 이터러블인 리스트를 활용

datas = [10,20,30,40,50]

for data in datas:
    print(f'데이터:{data}')

데이터:10
데이터:20
데이터:30
데이터:40
데이터:50


#### range() 함수 활용

`range(s, e, step)`: s값부터 e-1값까지의 step 간격을 가지는 수열 이터러블을 만드는 함수

In [32]:
# 0~4까지의 1의 간격을 가지는 수열 이터러블
for i in range(0,5):
    print(f'데이터: {i}')

0번째 반복
1번째 반복
2번째 반복
3번째 반복
4번째 반복


In [10]:
# 0~9까지의 2의 간격을 가지는 수열 이터러블
for i in range(0,10,2):
    print(f'데이터: {i}')

데이터: 0
데이터: 2
데이터: 4
데이터: 6
데이터: 8


#### 누적 연산 활용

In [16]:
count = 0

for d in [0,1,2,3,4]:
    count += d ## 반복할 때마다 i를 더함   
    print(f'{d}를 더한 값은 {count}')

0를 더한 값은 0
1를 더한 값은 1
2를 더한 값은 3
3를 더한 값은 6
4를 더한 값은 10


### 2.3 반복 제어

#### if 문과 활용

In [12]:
# for문 안에서 if문을 활용
for a in range(1,10):
    if a >= 7:
        print(a)


7
8
9


#### 중단 및 건너뛰기
`break` : 포함된 반복문을 중단시킴  
`continue` : 이후 반복문 내의 코드를 실행하지 않고 다음 반복으로 넘김

In [13]:

for a in range(1,10):
    if a % 3 == 0: # 3로 나눈 나머지가 0이면
        continue
    if a % 5 == 0:
        break
    print(a)

1
2
4


#### enumerate() 활용
enumerate() 함수에 인자로 이터러블을 입력하여 반복하면 순서와 데이터가 묶여서 반환

In [17]:
datas = [10,20,30,40,50]

for i, v in enumerate(datas):
    print(f'순서:{i}, 데이터:{v}')
    
    

순서:0, 데이터:10
순서:1, 데이터:20
순서:2, 데이터:30
순서:3, 데이터:40
순서:4, 데이터:50


### 2.4 while 반복문
while 반복문은 특정 상황까지의 반복을 위한 반복문.   
while 명령어 옆의 bool값을 통해 반복을 결정

In [1]:
i = 0

# i값이 10보다 작으면 반복
# i값이 10보다 커지는순간 반복정지
while i<10:
# 반복마다 i값이 1씩증가
    i += 1
    print(i)


1
2
3
4
5
6
7
8
9
10


In [2]:
i = 0

# if와 break 활용한 반복정지
while True:
    i += 1
    if i > 10:
        break
    print(i)


1
2
3
4
5
6
7
8
9
10


### 2.5 중첩 반복문

In [14]:
# 0~4 반복
for i in range(5):
    print('-----')

    # 0~4 반복안에 4~0 반복하여 25번 반복
    for j in range(5,0,-1):
        print(f'<{i}{j}>')


-----
<05>
<04>
<03>
<02>
<01>
-----
<15>
<14>
<13>
<12>
<11>
-----
<25>
<24>
<23>
<22>
<21>
-----
<35>
<34>
<33>
<32>
<31>
-----
<45>
<44>
<43>
<42>
<41>


### [참고] if 문에서 in 연산 활용시 특정 값이 이터러블내에 포함되어있으면 True

In [35]:
# if 데이터 in 이터러블

if 0 in [1,2,3,4]:
    print('zero in')

if 1 in [1,2,3,4]:
    print('one in')

one in


### 2. 실습


#### [실습1] 구구단 19단 출력하기  
`19 X 1 = 19`  
`19 X 2 = 38 ... ` 


In [36]:
#1. 참고
print(f'{19} X {1} = {19}')

19 X 1 = 19


#### [실습2] 아래의 숫자 리스트 *x* 에서 10 이상인 숫자만 따로 모아 합계 계산하기

In [37]:
#2. 
nums = [9, 10, 4, 22, 3, 19]

#### [실습3] 다음 리스트에 있는 숫자의 누적 합을 출력하세요. 단 *가 나오면 건너뛰고  - 가 나오면 반복을 중지

    출력결과
    1
    3
    7
    12
    19

In [20]:
nums2 = [1, 2, '*', 4, 5, '*', 7, '-', 9]

#### [실습4] 다음 리스트 안에 입력된 이름으로 Customer 인스턴스를 생성하세요. 이때 for문 안에서 Customer 인스턴스가 생성되고 고객 번호는 1씩 증가하는 순서입니다.

In [22]:
class Customer:

    def __init__(self, name, c_id):
        self.name = name
        self.c_id = c_id
        self.amount = 0

    def add_amount(self, amount):
        self.amount += amount
        # self.amount = self.amount + amount

    def sub_amount(self, amount):
        self.amount -= amount

    def get_amount(self):
        return self.amount

In [ ]:
names = ['김입금','나은행','최대출','신한나','국민협']


#### [실습5] for문을 두번 중첩하여 1~47번중 6개의 번호를 뽑는 로또 번호를 5개 생성하여 출력하세요 (숫자 중복 상관없음)

**random** 모듈    
`random` 모듈의 `randint()` 함수를 활용하여 랜덤 숫자 생성    
`randint(s,e)`: s~e 사이의 랜덤한 수 생성


In [29]:
import random


### 4.1 numpy를 활용한 배열
**numpy**는 **ndarray**라는 형식을 활용해서 다차원의 배열형식을 만들고 다양한 연산과 처리를 지원
- 배열은 리스트와 비슷하지만 구조적인 차이로 크기가 고정됨
- 배열은 여러개의 **축(axis)** 이 있는 다차원의 **형상(shape)** 을 가짐 

#### 배열 특징
- 리스트와 외부적으로는 유사하지만 내부적으로 많은 차이 존재
- 메모리 영역을 미리 계산하여 공간을 할당
- 항목의 타입을 미리 지정해야 생성가능
- 항목의 형상(개수) 가 정해져야 생성 가능
- 한번 정해진 형상(개수)는 변경불가
- 데이터 접근속도와 연산 효율이 좋음
- 공간의 활용성이 떨어짐

<img src="./img/20240601_225311.png"  width = 600 align=""></img>    


#### 배열생성
> 구현된 이터러블을 활용해 asarray()로 생성: np.asarray(iterable)    
> 지정 모형의 0으로 초기화 시키기: np.zeros((3,2))    
> 지정 모형의 1으로 초기화 시키기: np.ones((3,2))    
> 지정 모형의 0~1 랜덤 초기화 시키기: np.random.rand(3,2)   

In [100]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# 넘파이 모듈임포트
import numpy as np

In [3]:
# array() 함수로 배열 생성
x = [1, 2, 4, 8]
y = np.array(x)
print(y)
# shape 변수로 형상 확인
print(y.shape)

[1 2 4 8]
(4,)


##### 다차원 배열 형상 이해
<img src="./img/array1.png"  width = 640 ></img>

In [4]:
# 다차원 배열
array1d = np.array([1,2,3,4,5])

array2d = np.array([[1,2,3,4,5],
                    [6,7,8,9,0]])

array3d = np.array([[[1,2,3,4,5],
                     [6,7,8,9,0]],
                    [[2,3,4,5,6],
                     [7,8,9,0,1]],
                    [[3,4,5,6,7],
                     [8,9,0,1,2]]])

print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(5,)
(2, 5)
(3, 2, 5)


#### 다차원 배열 인덱싱

In [5]:
print(array1d[0])
print(array2d[0,2])
print(array3d[0,1,3])

1
3
9


In [6]:
print(array2d[0,1:4])

[2 3 4]


In [7]:
print(array3d[0, 1, 2:4])

[8 9]


In [8]:
print(array3d[0,:,1])

[2 7]


In [9]:
print(array3d[:,:, 0])

[[1 6]
 [2 7]
 [3 8]]


In [10]:
print(array3d[..., 0])

[[1 6]
 [2 7]
 [3 8]]


#### 인덱싱을 활용한 수정

In [11]:
array2d[0,1] = 10
array2d

array([[ 1, 10,  3,  4,  5],
       [ 6,  7,  8,  9,  0]])

In [12]:
array2d[0] = [2,3,4,5,6]
array2d

array([[2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

### 4.2 다차원 배열 연산

#### 배열에서 연산자 활용
배열에서 연산자 활용시 같은 인덱스에 해당하는 데이터간 일괄연산이 진행

In [17]:
# 일괄 산술 연산
array2d * 2 + 1

array([[ 5,  7,  9, 11, 13],
       [13, 15, 17, 19,  1]])

In [14]:
# 다양한 연산 함수 제공
print(np.sqrt(y)) # 제곱근
print(np.power(y, 2)) # 거듭제곱
print(np.log(y)) # 자연로그
print(np.exp(y)) # 지수

[1.         1.41421356 2.         2.82842712]
[ 1  4 16 64]
[0.         0.69314718 1.38629436 2.07944154]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


#### 원하는 축을 선택하여 연산
배열 연산 함수의 axis 인자 활용

In [15]:
array2d

array([[2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

In [16]:
# sum 함수를 활용하여 배열내 데이터 더하기 연산
np.sum(array2d)

50

In [117]:
# axis 인자에 0을 할당하여 0번 축으로 더하기
np.sum(array2d, axis = 0)

array([ 8, 10, 12, 14,  6])

In [120]:
np.sum(array2d, axis = 1)

array([20, 30])

In [121]:
array3d

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[2, 3, 4, 5, 6],
        [7, 8, 9, 0, 1]],

       [[3, 4, 5, 6, 7],
        [8, 9, 0, 1, 2]]])

In [122]:
np.sum(array3d, axis = 0)

array([[ 6,  9, 12, 15, 18],
       [21, 24, 17, 10,  3]])

In [123]:
np.sum(array3d, axis = 2)

array([[15, 30],
       [20, 25],
       [25, 20]])

### 4.3 배열의 형상 변환
numpy는 배열의 형상을 바꿔주는 다양한 함수 제공   
- 형상 변환 시 절대적인 배열의 크기는 변할 수 없음 

In [124]:
# reshape(배열, 형상) 배열을 입력한 형상으로 재구성
np.reshape(array3d,(30,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 3, 4,
       5, 6, 7, 8, 9, 0, 1, 2])

In [125]:
# reshape는 순서대로 재구성
np.reshape(array3d,(5,6))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 2, 3],
       [4, 5, 6, 7, 8, 9],
       [0, 1, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [126]:
np.reshape(array3d,(5,2,3))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [1]:
# -1을 활용하여 남은 형상 구현
np.reshape(array3d,(5,2,-1))

NameError: name 'np' is not defined

In [127]:
# 형상에 1을 입력하여 비어있는 차원을 추가할 수 있음
np.reshape(array1d,(1,5))

array([[1, 2, 3, 4, 5]])

In [130]:
# expand_dims 함수를 활용하여 원하는 축에 비어있는 차원을 추가
ed = np.expand_dims(array1d, axis = 0)
print(ed)
print(ed.shape)

[[1 2 3 4 5]]
(1, 5)


In [131]:
ed = np.expand_dims(array1d, axis = 1)
print(ed)
print(ed.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [133]:
# transpose 함수를 활용하여 역행렬 형태로 변환 가능
np.transpose(array2d)

array([[2, 6],
       [3, 7],
       [4, 8],
       [5, 9],
       [6, 0]])

### 4. 실습

#### [실습1] 다음 배열(arr2d)의 형상을 출력하고  0번축의 0 ~ 2번, 1번축의 2 ~ 4번에 해당하는 데이터를 출력하세요


In [19]:
import numpy as np

arr2d = np.array([[1,2,3,4,5],
                [5,6,7,8,9],
                [9,1,2,3,4],
                [5,6,7,8,9],
               ])


#### [실습2] 배열(arr2d)에 1번축 값들의 합으로 표현된 배열을 만들고 출력하세요


#### [실습3] 배열(arr2d)의 형상을 (2,2,5)로 변환하여 arr3d 변수에 할당하세요


#### [실습4] arr3d 배열에서 0,1 번축의 데이터는 모두 선택하고 마지막 축의 2번 인덱스에 해당하는 배열만 슬라이싱하여 출력하세요


#### [실습5] 중첩 반복 문을 활용하여 arr2d 배열의 데이터에 하나씩 접근하여 출력하세요


#### End of script