# Python 기초 문법

`작성자: 최원칠 강사`   
`traveler4d@gmail.com`


### 주요 내용

1. 파이썬의 기본 정의와 데이터 타입에 대한 이해
2. 파이썬 기본 제어문에 대한 이해
3. 파이썬 기본 데이터구조에 대한 이해



## 3. 여러 값을 묶은 데이터구조

`1`, `'파이썬'`처럼 하나의 값이 아니라 여러개의 값을 특정 구조로 저장

- 리스트(list)
- 튜플(tuple), 문자열(str)
- 사전(dictionary)

### 3.1. 가변 시퀀스 리스트

#### 리스트 구조
<img src="./img/20240601_214456.png"  width = 600 align=""></img>    

#### 리스트 특징
- 여러 데이터를 순서대로 연결시킨 가변적인 시퀀스 데이터 구조
- 순서(index)를 가지고 있음
- 여러 타입을 동시에 지니며 확장이 유연함
- 자유롭게 데이터를 수정하고 추가 가능
- 데이터를 순서대로 따라가야 접근 가능하여 접근 속도가 느림
- 메모리 공간의 활용성이 좋음

#### 리스트 생성
- 대괄호를 사용하여 빈 리스트를 표시하기: []
- 대괄호를 사용하여 쉼표로 항목 구분하기: [a], [a, b, c]
- 리스트 컴프리헨션 사용하기: [x for x in iterable]
- 내장함수 생성자를 사용하기: list() 또는 list(iterable)

In [5]:
# 비어있는 리스트 생성
empty = [] 
print(empty)

# 데이터를 넣어 리스트 생성
point = [5000, 6000, 7000, 6000, 9000]
print(point)

[]
[5000, 6000, 7000, 6000, 9000]


In [6]:
# 다양한 타입이 들어올 수 있음
types = ['파이썬', 5000, '기초', 6.215, '사전학습', True]
print(types)

['파이썬', 5000, '기초', 6.215, '사전학습', True]


In [7]:
# list() 함수 활용하여 생성 (형변환)
empty = list() # empty = []
print(empty)
seq = list(range(1, 20))
print(seq)

[]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [8]:
# for문과 if문을 활용한 리스트생성 (컴프리헨션)
seq_num = [x for x in range(1,10)]
print(seq_num)

seven_mul = [x for x in range(1,101) if x%7==0]
print(seven_mul)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]



#### 리스트의 메서드
> append(x): x를 맨뒤에 추가  
> extend(x) : x를 이어 붙이기(구조내 요소를 추가)  
> sort() : 내부 요소를 정렬  
> reverse() : 내부 요소를 반대로 구성   
> pop() : 마지막 순서 항목을 반환후 리스트에서 제거   
> clear() : 모든 항목을 제거   
> count(x) : x 가 리스트에 나타나는 횟수를 반환
> insert(i,x) : i순서에 x를 삽입    


In [9]:
# append : 리스트 맨뒤에 항목 추가하기

point = [5000, 6000, 7000, 6000, 9000]
point.append(10000)
point

[5000, 6000, 7000, 6000, 9000, 10000]

In [2]:
# extend : 또다른 리스트를 이어 붙이기(구조내 요소를 추가)
# + 연산을 활용하여 이어 붙이기 가능

point = [5000, 6000, 7000, 6000, 9000]
point.append([6000, 5000])
print(point)

point = [5000, 6000, 7000, 6000, 9000]
point.extend([6000, 5000])
print(point)

concat = [5000, 6000, 7000, 6000, 9000] + [6000, 5000]
print(concat)

[5000, 6000, 7000, 6000, 9000, [6000, 5000]]
[5000, 6000, 7000, 6000, 9000, 6000, 5000]
[5000, 6000, 7000, 6000, 9000, 6000, 5000]


In [12]:
# sort : 내부 요소를 정렬
# reverse : 내부 요소를 반대로 구성

point = [9000, 5000, 6000, 7000, 6000]
point.sort()
print(point)

point = [9000, 5000, 6000, 7000, 6000]
point.reverse()
print(point)

[5000, 6000, 6000, 7000, 9000]
[6000, 7000, 6000, 5000, 9000]


### 3.2. 인덱싱과 슬라이싱 

#### 인덱싱
`데이터구조[인덱스]` 형식을 활용하여 원하는 데이터에 접근하는 방식    
인덱스는 데이터구조에 따라 다양한 형태로 존재

<img src="./img/20240601_215023.png"  width = 500 align=""></img>    


In [76]:
# [index]를 활용한 데이터 선택
#     index는 0부터 시작 : 첫번째 값이 0
point = [5000, 6000, 7000, 6000, 9000]

print(point[0])
print(point[2])
# 음수를 활용하여 역순으로 인덱싱 가능
print(point[-1])

5000
7000
9000


#### 슬라이싱
`데이터구조[시작인덱스:끝인덱스]` 형식으로 범위를 지정하여 데이터구조의 부분을 가져옴

In [68]:
# [start:end]을 활용해 범위 지정 가능(슬라이싱), 끝 인덱스 미포함
point = [5000, 6000, 7000, 6000, 9000]
print(point[2:4])
# 앞에 0은 생략
print(point[:3])

[7000, 6000]
[5000, 6000, 7000]


In [69]:
# 음수 인덱스로 뒤에순서를 지정 가능
point = [5000, 6000, 7000, 6000, 9000]
# 마지막 인덱스는 생략
print(point[-2:])

[6000, 9000]


#### 인덱싱으로 데이터 수정

In [70]:
# 인덱스를 활용한 업데이트
point[3] = 60000
point

[5000, 6000, 7000, 60000, 9000]

In [71]:
# 인덱스가 없으면 에러
point[6] = 60000

IndexError: list assignment index out of range

In [72]:
# 인덱스에 접근하여 삭제
del point[3]
point

[5000, 6000, 7000, 9000]

### 3.3. 불변 시퀀스 튜플(tuple)과 문자열(str)
튜블과 문자열은 내부적으로 구조를 바꿀수 없는 불변 시퀀스형

#### 튜플 특징
- 여러 데이터를 묶음으로 보관하는 불변 시퀀스 데이터 구조
- 리스트처럼 순서대로 여러 데이터를 보유
- 리스트와 반대로 데이터 추가 및 수정 불가능
- 리스트에 비해 가볍고 빠른 접근 속도를 가짐

#### 튜플 생성 및 표현
> 튜플은 ()를 활용해서 만들 수 있고, 소괄호는 생략 가능


In [37]:
aa = (1, 2, 3)
bb = '아침', '점심', '저녁'

print(type(aa))
print(type(bb))

<class 'tuple'>
<class 'tuple'>


In [39]:
# 인덱싱 및 슬라이싱 가능
print(aa[0])
print(bb[1:])

1
('점심', '저녁')


In [40]:
# 추가/업데이트 불가능, 내부 변환 메소드도 없음
aa[0] = 4

TypeError: 'tuple' object does not support item assignment

In [45]:
# 튜플 요소의 순서를 맞추어 변수 할당 가능

a, b = ('아침', '점심')
print(a)
print(b)

아침
점심


#### 문자열 특징
- 유니코드 코드 포인트의 불변 시퀀스 데이터구조
- 문자열의 변환을 반환하는 다양한 메소드 포함 
- 리스트와 동일하게 순서로 인덱싱
- 인덱싱을 활용한 데이터 수정 불가

#### 문자열 데이터구조 활용
자료형에서 본 문자열은 실제 불변시퀀스의 데이터구조형태를 가짐, 불변시퀀스형이지만 다양한 메소드가 있음(복사 반환)
> replace(x,y) : x문자열을 y문자열로 대체  
> strip() : 앞뒤 공백 제거  
> split(x) : x문자열을 기준으로 분리하여 리스트생성    
> encode() : 문자열의 인코딩 버전 변환 기본은 utf-8   
> find(substr) : 문자열내에 포함되는 서브 문자열 첫 인덱스 반환환


In [77]:
# 인덱싱과 슬라이싱 가능
# 수정은 불가능
s = '파이썬 기초 데이터구조'
print(s[2])
print(s[4:8])

썬
기초 데


In [78]:
# replace() : 원하는 부분문자열을 다른 문자열로 대체
s = '파이썬 기초 데이터구조'
s1 = s.replace('기초', '심화')
s1

'파이썬 심화 데이터구조'

In [79]:
# strip() : 앞뒤 공백 제거
s = '   파이썬 기초 데이터구조\n'
s = s.strip()
s

'파이썬 기초 데이터구조'

In [80]:
# split() : 원하는 문자열을 기준으로 분리하여 리스트생성
s = '파이썬 기초 데이터구조'
s1 = s.split(' ') # 공백(띄어쓰기) 기준으로 분리
s1


['파이썬', '기초', '데이터구조']

### 3.4. 해쉬셋과 딕셔너리
순서가 아닌 해쉬를 기반으로 데이터를 구조적으로 저장

#### 해쉬셋(집합) 특징
- 해시 가능 객체의 순서가 없고 중복이 없는 컬렉션
- 해시 테이블을 사용한 데이터구조
- 동일 항목은 같은 위치에 참조되기 때문에 중복 항목이 없음
- 배열, 리스트와 다르게 저장 순서를 기억하지 않음
- 데이터 저장속도가 빠름

<img src="./img/20240601_220240.png"  width = 400 align=""></img>    


#### 해쉬셋 생성 과 표현
> 해쉬셋은 {}로 표현되며 해쉬특성으로 인해 내부 요소는 고유값을 가지고 순서가 없음

In [81]:
# 순서가 없는 해쉬셋
s = {'돈까스','치킨','덮밥'}
s.add('우동')
s

{'덮밥', '돈까스', '우동', '치킨'}

In [82]:
set(('돈까스','치킨','덮밥','덮밥'))

{'덮밥', '돈까스', '치킨'}

In [83]:
# 중복이 되지 않는 해쉬셋
s = {'돈까스','치킨','덮밥','치킨'}
s.add('덮밥')
s

{'덮밥', '돈까스', '치킨'}

#### 딕셔너리 특징

- 해시 가능 객체를 특정 객체와 매핑하여 *키(key)* 와 *값(value)* 매핑구조를 가짐
- 해시 가능 하지 않은 객체들(리스트, 딕셔너리)등은 *key*로 사용불가
- *값(value)* 은 어떤 타입의 데이터도 사용가능
- *key*는 해쉬특성을 가져 찾는 속도와 저장속도가 빠름
- 웹통신 데이터뭉치인 json형과 비슷한 구조로 많이 활용

<img src="./img/20240601_220253.png"  width = 600 align=""></img>   

#### 딕셔너리 생성
> {} 안에 쉼표로 구분된 key:value 쌍을 나열하기 {key1:value1 , key2:value2}   
> 딕셔너리 컴프리헨션 사용하기 {x: x ** 2 for x in range(10)}   
> 함수 사용하기: dict()   성 


In [84]:
# 키:값 매핑으로 딕셔너리 생성
product1 = {'제품명':'팜봇', '가격':500000, '카테고리':'Aiot'}
product1

{'제품명': '팜봇', '가격': 500000, '카테고리': 'Aiot'}

In [85]:
# 키를 입력하여 인덱싱
product1['제품명']

'팜봇'

In [86]:
# 없는키는 에러
product1['할인율']

KeyError: '할인율'

In [87]:
# 메서드 get()을 활용하면 에러 방지
product1.get('할인율',0)

0

In [88]:
# 시퀀스 연산자에 새로운 키를 넣고 할당하여 키:값 추가
product1['재고'] = 10
product1

{'제품명': '팜봇', '가격': 500000, '카테고리': 'Aiot', '재고': 10}

In [89]:
# 시퀀스 연산자에 기존 키를 넣고 할당하여 값 변경
product1['재고'] = 5
product1


{'제품명': '팜봇', '가격': 500000, '카테고리': 'Aiot', '재고': 5}

In [90]:
# del 연산을 활용한 키:값 제거
del product1['카테고리']
product1

{'제품명': '팜봇', '가격': 500000, '재고': 5}

In [91]:
# 키 목록 반환
product1.keys()

dict_keys(['제품명', '가격', '재고'])

In [92]:
# 리스트로 키 목록 반환
list(product1)

['제품명', '가격', '재고']

In [93]:
# 값 목록 반환
product1.values()

dict_values(['팜봇', 500000, 5])

In [94]:
# 반복문에는 키가 이터러블
for p in product1:
    print(p)

제품명
가격
재고


In [95]:
# 계층 구조로 구성
product1['카테고리'] = ['AI','Aiot','Iot','farm']
product1

{'제품명': '팜봇', '가격': 500000, '재고': 5, '카테고리': ['AI', 'Aiot', 'Iot', 'farm']}

In [96]:
# 계층적 구조를 가지는 딕셔너리
d = {
    'id': 1,
    'name': '원칠',
    'company': {
        'name': 'taveler4d',
        'site': 'aaa.www.ggg',
        'phone': '02-2222-2222',
        'city': '구로디지털단지'},
    'project': [
        {'name': 'pandas', 'pid': '0014'},
        {'name': 'aiot', 'pid': '0023'}
    ],
    'phone': '010-1111-2222'
}

print(d['company']['city'])
print(len(d['project']))
print(d['project'][0]['name'])

구로디지털단지
2
pandas


### 3. 실습


#### [실습1] 관심있는 메뉴 3개를 묶은 menu 리스트를 생성하고 append( )로 메뉴 하나 더 추가하세요


#### [실습2] menu에서 세번째 메뉴를 '우동'으로 변경하고 세번째~마지막 메뉴를 선택하여 출력하세요

#### [실습3] '메뉴이름' 키에는 메뉴이름이, '가격' 키에는 해당 메뉴의 가격이 입력된 딕셔너리 하나를 생성하세요


#### [실습4] 다음 리스트 내부에 값을 1씩 더한 값으로 수정하여 리스트를 출력하세요

In [97]:
nums = [1,2,3,4,5]

#### [실습5] 다음 두개의 리스트를 활용하여 실습3 에서 구성한 형태의 딕셔너리를 3개 만들고 이를 보관하는 리스트를 만들어 출력하세요

In [98]:
menu = ['치킨','피자','국밥']
price = [20000, 23000, 10000]


#### [실습6] 실습5에서 만든 리스트에서 1번 메뉴의 가격을 인덱싱하여 출력하세요

#### [실습7] 다음 세 리스트를 이어붙이고 이름 순으로 정렬하여 출력하세요


In [99]:
list1 = ['a','f','c']
list2 = ['b','e']
list3 = ['a','f']


#### [실습8] 실습7에서 만든 리스트에서 중복을 제거하여 출력하세요

#### [실습9] 다음 s1 문자열에서 stop_words에 해당하는 단어를 뺀 단어 리스트를 만들어 출력하세요

    출력 결과
    ['삼성', '빅데이터', '데이터분석', '파이썬', '시각화', '판다스']

In [67]:
s1 = '  새싹 빅데이터 데이터분석 데이터구조 파이썬 시각화 판다스     '
stop_words = '데이터구조'

#### [실습10] 3개의 딕셔너리를 for문과 인덱싱을 활용하여 다음과 같은 리스트-딕셔너리 구조로 만들어 출력하세요

    출력결과
    [{'주문자': 'G밸리', '상품명': '노트북', '가격': 200}, {'주문자': 'G밸리', '상품명': '샴푸', '가격': 2}, {'주문자': '데이터분석', '상품명': '초코렛', '가격': 1}, {'주문자': '파이썬', '상품명': '자전거', '가격': 15}, {'주문자': '파이썬', '상품명': '셔츠', '가격': 1}, {'주문자': '파이썬', '상품명': '초코렛', '가격': 1}]


In [75]:
users = {'123':'G밸리',
         '124':'파이썬',
         '125':'데이터분석',}

products = {'a':['노트북', 200],
            'b':['자전거', 15],
            'c':['샴푸', 2],
            'd':['셔츠', 1],
            'e':['초코렛', 1]}

orders = [{'user_id':'123', 'products':['a','c']},
         {'user_id':'125', 'products':['e']},
         {'user_id':'124', 'products':['b','d','e']}]



## 4. numpy 배열
파이썬 내장 데이터구조가 아닌 외부 라이브러리로 제공되는 대표적인 데이터구조



### 4.1 numpy를 활용한 배열
**numpy**는 **ndarray**라는 형식을 활용해서 다차원의 배열형식을 만들고 다양한 연산과 처리를 지원
- 배열은 리스트와 비슷하지만 구조적인 차이로 크기가 고정됨
- 배열은 여러개의 **축(axis)** 이 있는 다차원의 **형상(shape)** 을 가짐 

#### 배열 특징
- 리스트와 외부적으로는 유사하지만 내부적으로 많은 차이 존재
- 메모리 영역을 미리 계산하여 공간을 할당
- 항목의 타입을 미리 지정해야 생성가능
- 항목의 형상(개수) 가 정해져야 생성 가능
- 한번 정해진 형상(개수)는 변경불가
- 데이터 접근속도와 연산 효율이 좋음
- 공간의 활용성이 떨어짐

<img src="./img/20240601_225311.png"  width = 600 align=""></img>    


#### 배열생성
> 구현된 이터러블을 활용해 asarray()로 생성: np.asarray(iterable)    
> 지정 모형의 0으로 초기화 시키기: np.zeros((3,2))    
> 지정 모형의 1으로 초기화 시키기: np.ones((3,2))    
> 지정 모형의 0~1 랜덤 초기화 시키기: np.random.rand(3,2)   

In [100]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# 넘파이 모듈임포트
import numpy as np

In [3]:
# array() 함수로 배열 생성
x = [1, 2, 4, 8]
y = np.array(x)
print(y)
# shape 변수로 형상 확인
print(y.shape)

[1 2 4 8]
(4,)


##### 다차원 배열 형상 이해
<img src="./img/array1.png"  width = 640 ></img>

In [4]:
# 다차원 배열
array1d = np.array([1,2,3,4,5])

array2d = np.array([[1,2,3,4,5],
                    [6,7,8,9,0]])

array3d = np.array([[[1,2,3,4,5],
                     [6,7,8,9,0]],
                    [[2,3,4,5,6],
                     [7,8,9,0,1]],
                    [[3,4,5,6,7],
                     [8,9,0,1,2]]])

print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(5,)
(2, 5)
(3, 2, 5)


#### 다차원 배열 인덱싱

In [5]:
print(array1d[0])
print(array2d[0,2])
print(array3d[0,1,3])

1
3
9


In [6]:
print(array2d[0,1:4])

[2 3 4]


In [7]:
print(array3d[0, 1, 2:4])

[8 9]


In [8]:
print(array3d[0,:,1])

[2 7]


In [9]:
print(array3d[:,:, 0])

[[1 6]
 [2 7]
 [3 8]]


In [10]:
print(array3d[..., 0])

[[1 6]
 [2 7]
 [3 8]]


#### 인덱싱을 활용한 수정

In [11]:
array2d[0,1] = 10
array2d

array([[ 1, 10,  3,  4,  5],
       [ 6,  7,  8,  9,  0]])

In [12]:
array2d[0] = [2,3,4,5,6]
array2d

array([[2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

### 4.2 다차원 배열 연산

#### 배열에서 연산자 활용
배열에서 연산자 활용시 같은 인덱스에 해당하는 데이터간 일괄연산이 진행

In [17]:
# 일괄 산술 연산
array2d * 2 + 1

array([[ 5,  7,  9, 11, 13],
       [13, 15, 17, 19,  1]])

In [14]:
# 다양한 연산 함수 제공
print(np.sqrt(y)) # 제곱근
print(np.power(y, 2)) # 거듭제곱
print(np.log(y)) # 자연로그
print(np.exp(y)) # 지수

[1.         1.41421356 2.         2.82842712]
[ 1  4 16 64]
[0.         0.69314718 1.38629436 2.07944154]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


#### 원하는 축을 선택하여 연산
배열 연산 함수의 axis 인자 활용

In [15]:
array2d

array([[2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

In [16]:
# sum 함수를 활용하여 배열내 데이터 더하기 연산
np.sum(array2d)

50

In [117]:
# axis 인자에 0을 할당하여 0번 축으로 더하기
np.sum(array2d, axis = 0)

array([ 8, 10, 12, 14,  6])

In [120]:
np.sum(array2d, axis = 1)

array([20, 30])

In [121]:
array3d

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[2, 3, 4, 5, 6],
        [7, 8, 9, 0, 1]],

       [[3, 4, 5, 6, 7],
        [8, 9, 0, 1, 2]]])

In [122]:
np.sum(array3d, axis = 0)

array([[ 6,  9, 12, 15, 18],
       [21, 24, 17, 10,  3]])

In [123]:
np.sum(array3d, axis = 2)

array([[15, 30],
       [20, 25],
       [25, 20]])

### 4.3 배열의 형상 변환
numpy는 배열의 형상을 바꿔주는 다양한 함수 제공   
- 형상 변환 시 절대적인 배열의 크기는 변할 수 없음 

In [124]:
# reshape(배열, 형상) 배열을 입력한 형상으로 재구성
np.reshape(array3d,(30,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 3, 4,
       5, 6, 7, 8, 9, 0, 1, 2])

In [125]:
# reshape는 순서대로 재구성
np.reshape(array3d,(5,6))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 2, 3],
       [4, 5, 6, 7, 8, 9],
       [0, 1, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [126]:
np.reshape(array3d,(5,2,3))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [1]:
# -1을 활용하여 남은 형상 구현
np.reshape(array3d,(5,2,-1))

NameError: name 'np' is not defined

In [127]:
# 형상에 1을 입력하여 비어있는 차원을 추가할 수 있음
np.reshape(array1d,(1,5))

array([[1, 2, 3, 4, 5]])

In [130]:
# expand_dims 함수를 활용하여 원하는 축에 비어있는 차원을 추가
ed = np.expand_dims(array1d, axis = 0)
print(ed)
print(ed.shape)

[[1 2 3 4 5]]
(1, 5)


In [131]:
ed = np.expand_dims(array1d, axis = 1)
print(ed)
print(ed.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [133]:
# transpose 함수를 활용하여 역행렬 형태로 변환 가능
np.transpose(array2d)

array([[2, 6],
       [3, 7],
       [4, 8],
       [5, 9],
       [6, 0]])

### 4. 실습

#### [실습1] 다음 배열(arr2d)의 형상을 출력하고  0번축의 0 ~ 2번, 1번축의 2 ~ 4번에 해당하는 데이터를 출력하세요


In [19]:
import numpy as np

arr2d = np.array([[1,2,3,4,5],
                [5,6,7,8,9],
                [9,1,2,3,4],
                [5,6,7,8,9],
               ])


#### [실습2] 배열(arr2d)에 1번축 값들의 합으로 표현된 배열을 만들고 출력하세요


#### [실습3] 배열(arr2d)의 형상을 (2,2,5)로 변환하여 arr3d 변수에 할당하세요


#### [실습4] arr3d 배열에서 0,1 번축의 데이터는 모두 선택하고 마지막 축의 2번 인덱스에 해당하는 배열만 슬라이싱하여 출력하세요


#### [실습5] 중첩 반복 문을 활용하여 arr2d 배열의 데이터에 하나씩 접근하여 출력하세요



## 5. 스택과 큐
기본 데이터구조를 활용한 추상 자료 구조


### 5.1 Stack
- LIFO 선입 후출의 방식으로 데이터를 저장하고 접근
- 내부적으로 배열 또는 리스트 구조를 활용 (파이썬에선 리스트)
- append() 구조의 맨앞에 항목 추가 (인덱스상으로 맨끝)
- pop() 맨앞 항목을 구조에서 제거하고 반환 (인덱스상으로 맨끝)


<img src="./img/20240909_133427.png"  width = 600 align=""></img>


In [1]:
# 스택을 리스트로 구현
stack = []

# 스택에 요소 추가 (push)
stack.append('A')
stack.append('B')
stack.append('C')

print("스택 상태:", stack)

# 스택에서 요소 제거 (pop)
print("팝된 요소:", stack.pop())  # C
print("팝된 요소:", stack.pop())  # B

print("스택 상태:", stack)

스택 상태: ['A', 'B', 'C']
팝된 요소: C
팝된 요소: B
스택 상태: ['A']


### 5.2 Queue
- FIFO 선입 선출의 방식으로 데이터를 저장하고 접근
- 내부적으로 배열 또는 리스트 구조를 활용 (파이썬에선 리스트)
- put() 구조의 맨끝에 항목 추가 
- get() 맨앞 항목을 구조에서 제거하고 반환


<img src="./img/20240909_133443.png"  width = 600 align=""></img>

In [2]:
import queue

# 큐 생성 (Queue)
q = queue.Queue()

# 큐에 요소 추가 (enqueue)
q.put('1')
q.put('2')
q.put('3')

# 큐가 비어있을때 까지 반복
while not q.empty():
    print("큐에서 나온 요소:", q.get())

큐에서 나온 요소: 1
큐에서 나온 요소: 2
큐에서 나온 요소: 3


### 5.3 Deque
- 양방향 접근이 가능한 Queue의 확장 인터페이스로 속도향상
- FIFO, LIFO 가 다 가능하며 상황에 따라 원하는 입출 방식을 정할 수 있음
- append() 구조의 오른쪽에 항목 추가
- appendleft() 구조의 왼쪽에 항목 추가
- pop() 구조의 오른쪽에서 항목 제거하고 반환
- popleft() 구조의 왼쪽에서 항목 제거하고 반환

<img src="./img/20240909_133501.png"  width = 600 align=""></img>

In [3]:
from collections import deque

# 데크 생성
dq = deque()

# 데크에 요소 추가 (append: 뒤쪽 추가, appendleft: 앞쪽 추가)
dq.appendleft('X')
dq.append('A')
dq.append('B')

print("데크 상태:", dq)

# 앞쪽에서 요소 제거 (popleft)
print("앞쪽에서 제거된 요소:", dq.popleft())  # X

# 뒤쪽에서 요소 제거 (pop)
print("뒤쪽에서 제거된 요소:", dq.pop())  # B

print("데크 상태:", dq)

데크 상태: deque(['X', 'A', 'B'])
앞쪽에서 제거된 요소: X
뒤쪽에서 제거된 요소: B
데크 상태: deque(['A'])


## 6. 트리구조

- 특정노드로 시작하여 자식 노드를 확장하며 밑으로 뻗어가는 자료구조
- 공간의 효율성을 올리면서 접근속도를 최대화 시키기 위해 사용
- 배열, 연결구조를 활용하여 구현가능

<img src="./img/20240909_135651.png"  width = 640 align=""></img>

### 6.1 이진 트리
- 자식노드를 2개만 가지는 트리 구조
- 데이터의 추가와 접근 속도의 밸런스를 맞춤
- 노드의 깊이가 하나 증가할 때 마다 최대 2배수로 노드가 늘어남
    - n층의 노드개수: 2의n승
- 노드의 접근 성능이 일반 연결리스트 보다 좋음
    - 최대 효율 log(n)
    - 최저 효율 n
- 최악의 경우 리스트와 동일한 접근속도가 나옴
- 탐색을 위해 반복문이 아닌 재귀방식을 사용
    - Preorder, Postorder, Inorder
- 직접 구현하거나 외부 라이브러리를 활용(bintrees)

<img src="./img/20240909_140136.png"  width = 640 align=""></img>   
***입력 노드의 값이 부모 노드 보다 크면 오른쪽 작으면 왼쪽으로 만들어지는 간단한 이진트리***

#### 구조에 따른 특징

| **구현 방식**            | **장점**                                                       | **단점**                                                  |
|-------------------------|--------------------------------------------------------------|----------------------------------------------------------|
| **배열(Array)**          | - 인덱스를 통한 빠른 접근<br>- 추가 포인터 관리 불필요<br>- 연속된 메모리 공간 사용으로 캐시 효율성 증가 | - 비효율적인 공간 사용(완전 이진 트리가 아닐 때)<br>- 크기 고정, 확장 어려움<br>- 동적 트리 관리 어려움 |
| **연결 리스트(Linked)**  | - 동적 메모리 사용으로 크기 유연<br>- 빈 공간 없이 필요한 만큼 메모리 사용<br>- 복잡한 트리 구조에 적합 | - 노드 접근 속도가 느림<br>- 포인터로 인한 추가 메모리 사용<br>- 포인터 관리의 복잡성 증가 |



In [5]:
class BSTNode:
    def __init__(self, key):
        self.left = None
        self.right = None
        self.value = key

    def insert(self, key):
        if key < self.value:
            if self.left is None:
                self.left = BSTNode(key)
            else:
                self.left.insert(key)
        elif key > self.value:
            if self.right is None:
                self.right = BSTNode(key)
            else:
                self.right.insert(key)

# 이진 탐색 트리 생성 및 삽입
itmes = [10,23,6,9,29,15,26,19,3]
root = BSTNode(17)
for v in itmes:
    root.insert(v)

### 6.2 재귀식 트리 탐색
- Preorder: 부모노드 -> 왼쪽노드 -> 오른쪽노드 순으로 탐색
- Postorder: 왼쪽노드 -> 오른쪽노드 -> 부모노드 순으로 탐색
- Inorder: 왼쪽노드 -> 부모노드 -> 오른쪽노드 순으로 탐색

<img src="./img/20240909_141656.png"  width = 640 align=""></img>   

In [6]:
class BSTNode:
    def __init__(self, key):
        self.left = None
        self.right = None
        self.value = key

    def insert(self, key):
        if key < self.value:
            if self.left is None:
                self.left = BSTNode(key)
            else:
                self.left.insert(key)
        elif key > self.value:
            if self.right is None:
                self.right = BSTNode(key)
            else:
                self.right.insert(key)

    # 전위 순회 (Pre-order Traversal)
    def pre_order(self):
        print(self.value, end=' ')  # 부모 노드 먼저 출력
        if self.left:
            self.left.pre_order()   # 왼쪽 자식 순회
        if self.right:
            self.right.pre_order()  # 오른쪽 자식 순회

    # 중위 순회 (In-order Traversal)
    def in_order(self):
        if self.left:
            self.left.in_order()    # 왼쪽 자식 순회
        print(self.value, end=' ')  # 부모 노드 출력
        if self.right:
            self.right.in_order()   # 오른쪽 자식 순회

    # 후위 순회 (Post-order Traversal)
    def post_order(self):
        if self.left:
            self.left.post_order()  # 왼쪽 자식 순회
        if self.right:
            self.right.post_order() # 오른쪽 자식 순회
        print(self.value, end=' ')  # 부모 노드 나중에 출력

# 이진 탐색 트리 생성 및 삽입
items = [10, 23, 6, 9, 29, 15, 26, 19, 3]
root = BSTNode(17)
for v in items:
    root.insert(v)

# 3가지 탐색 방법 출력
print("Pre-order Traversal (전위 순회):")
root.pre_order()  # 출력: 17 10 6 3 9 15 23 19 29 26

print("\nIn-order Traversal (중위 순회):")
root.in_order()   # 출력: 3 6 9 10 15 17 19 23 26 29

print("\nPost-order Traversal (후위 순회):")
root.post_order() # 출력: 3 9 6 15 10 19 26 29 23 17

Pre-order Traversal (전위 순회):
17 10 6 3 9 15 23 19 29 26 
In-order Traversal (중위 순회):
3 6 9 10 15 17 19 23 26 29 
Post-order Traversal (후위 순회):
3 9 6 15 10 19 26 29 23 17 

### 6.3 밸런스를 위한 다양한 트리
- 일반적인 이진트리는 상황에 따라 최악의 탐색시간을 초래할 수 있음
- 트리의 밸런스를 맞추기 위해 삽입 및 삭제시 특정 룰을 지정한 트리구조
    - 최대, 최소 힙트리
    - AVL 트리
    - 레드-블랙 트리
    - B 트리
- 데이터베이스는 B 트리를 기반으로 많이 구성

#### AVL 트리 예시
- 이진 트리 방식을 따르며 노드를 추가 하다 균형이 안맞으면 회전을 시켜 균형을 맞춤
- 층수의 차로 균형파악

<img src="./img/20240909_143449.png"  width = 640 align=""></img>   



In [8]:
# avl트리 예시

class AVLNode:
    def __init__(self, key):
        self.left = None
        self.right = None
        self.value = key
        self.height = 1  # 높이를 트래킹하여 균형을 유지

# AVL 트리 클래스
class AVLTree:
    # 노드의 높이를 가져오는 함수
    def get_height(self, node):
        if not node:
            return 0
        return node.height

    # 노드의 균형 인수를 계산하는 함수
    def get_balance(self, node):
        if not node:
            return 0
        return self.get_height(node.left) - self.get_height(node.right)

    # 왼쪽 회전 (Right-heavy tree를 균형 맞출 때 사용)
    def rotate_left(self, z):
        y = z.right
        T2 = y.left
        y.left = z
        z.right = T2
        z.height = 1 + max(self.get_height(z.left), self.get_height(z.right))
        y.height = 1 + max(self.get_height(y.left), self.get_height(y.right))
        return y

    # 오른쪽 회전 (Left-heavy tree를 균형 맞출 때 사용)
    def rotate_right(self, z):
        y = z.left
        T3 = y.right
        y.right = z
        z.left = T3
        z.height = 1 + max(self.get_height(z.left), self.get_height(z.right))
        y.height = 1 + max(self.get_height(y.left), self.get_height(y.right))
        return y

    # AVL 트리 삽입
    def insert(self, root, key):
        # 1. 기본적인 BST 삽입
        if not root:
            return AVLNode(key)
        elif key < root.value:
            root.left = self.insert(root.left, key)
        else:
            root.right = self.insert(root.right, key)

        # 2. 노드의 높이 업데이트
        root.height = 1 + max(self.get_height(root.left), self.get_height(root.right))

        # 3. 균형 인수 계산
        balance = self.get_balance(root)

        # 4. 균형이 깨졌을 때 회전 수행
        # LL 회전
        if balance > 1 and key < root.left.value:
            return self.rotate_right(root)
        # RR 회전
        if balance < -1 and key > root.right.value:
            return self.rotate_left(root)
        # LR 회전
        if balance > 1 and key > root.left.value:
            root.left = self.rotate_left(root.left)
            return self.rotate_right(root)
        # RL 회전
        if balance < -1 and key < root.right.value:
            root.right = self.rotate_right(root.right)
            return self.rotate_left(root)

        return root

    # 중위 순회 (In-order Traversal)
    def in_order(self, root):
        if root:
            self.in_order(root.left)
            print(root.value, end=" ")
            self.in_order(root.right)

# AVL 트리 생성 및 삽입
avl_tree = AVLTree()
root = None
items = [10, 23, 6, 9, 29, 15, 26, 19, 3]

for item in items:
    root = avl_tree.insert(root, item)

# 중위 순회 출력 (정렬된 상태로 출력)
print("In-order Traversal of AVL Tree:")
avl_tree.in_order(root)

In-order Traversal of AVL Tree:
3 6 9 10 15 19 23 26 29 